CREATE TABLE [dbo].[Sesh]
(
	[SeshID] INT IDENTITY (1,1) NOT NULL,
	[Date] NVARCHAR(50) NOT NULL,
	[Time] NVARCHAR (20) NOT NULL,
	[Venue] NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_SESH PRIMARY KEY (SeshID)
)
