CREATE TABLE [dbo].[Shout]
(
	[SeshToShout] INT NOT NULL,
	[Shouter] NVARCHAR (100) NOT NULL,
	[Amount] NVARCHAR (20),
	CONSTRAINT PK_SHOUT PRIMARY KEY (SeshToShout, Shouter),
	CONSTRAINT FK_SESH FOREIGN KEY (SeshToShout) REFERENCES Sesh (SeshID),
	CONSTRAINT FK_SHOUTER FOREIGN KEY (Shouter) REFERENCES Member (Email)
)
